import { React, useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import { useRouter } from 'next/router';

const Home = () => {
  const router = useRouter();
  const [transition, setTransition] = useState('');
  const [transform, setTransform] = useState('');

  function getStart() {
    // setTransition('all 1s ease-out')
    // setTransform('scale(2,2)')
    router.push('/weather');
  }

  return (
    <div>
      <Head>
        <title>PerSPective</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.png" />
      </Head>
      <Header type="index" />
      <div className={styles.btnContainer}></div>
      <div
        className={styles.startBtn}
        style={{ width: '10%', height: '10%', transition: { transition }, transform: { transform } }}
      >
        <Image src="/assets/start_btn.png" alt="" layout="fill" objectFit="contain" onClick={() => getStart()} />
      </div>
    </div>
  );
};

export default Home;
