import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header type="index" />
      <Image className={styles.startBtn} src="/assets/start_btn.png" alt="gift_pic" width={50} height={50} />
    </div>
  );
};

export default Home;
